### ISSUE TITLE
Routing error

### ISSUE THREAD

**Issue by alec-c4** [ankane/searchjoy#38]
Hi, 
i see strange behaviour of searchjoy gem. Just added gem, but there are errors in logs . 

```
server  | Started GET "/searchjoy/searches/recent" for ::1 at 2019-05-12 23:30:00 +0300
server  |    (2.0ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
server  |   ↳ /Users/alec/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/log_subscriber.rb:98
server  |
server  | ActionController::RoutingError (No route matches [GET] "/searchjoy/searches/recent"):
server  |
server  | actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
server  | web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
server  | web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
server  | web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
server  | web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
server  | actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
server  | railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
server  | railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
server  | activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
server  | activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
server  | activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
server  | railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
server  | actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
server  | request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
server  | actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
server  | rack (2.0.7) lib/rack/method_override.rb:22:in `call'
server  | rack (2.0.7) lib/rack/runtime.rb:22:in `call'
server  | activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
server  | actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
server  | actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
server  | rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
server  | webpacker (4.0.2) lib/webpacker/dev_server_proxy.rb:29:in `perform_request'
server  | rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
server  | railties (5.2.3) lib/rails/engine.rb:524:in `call'
server  | puma (3.12.1) lib/puma/configuration.rb:227:in `call'
server  | puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
server  | puma (3.12.1) lib/puma/server.rb:474:in `process_client'
server  | puma (3.12.1) lib/puma/server.rb:334:in `block in run'
server  | puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

PS: routes.rb does contains

```
  authenticate :user, lambda { |u| u.has_role? :admin } do
    mount Searchjoy::Engine, at: "searchjoy"
  end
```

**Comment by ankane** [comment]
Hey @alec-c4, this is likely something specific to your app. If you figure it out, please report back so others can benefit.
